server:
  port: 22223
  
spring:
  datasource:
    name: zk
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
#    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&amp;characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    druid:
    #初始化时建立物理连接的个数
      initial-size: 3
      #最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 10
      #获取连接时最大等待时间
      max-wait: 60000
      #配置监控页面访问账号密码
      stat-view-servlet:
        login-username: admin
        login-password: admin
      filter:
        stat:
        #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 1
  jpa:
#    open-in-view: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
#        hbm2ddl:
#          auto: update
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        format_sql: true

#zookeeper
zk:
  host: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
  namespace: kill-1
  lockPath: /lock/